spring.application.name=admin-server
# Spring Boot Admin Server - application.properties

server.port=8900

# Enable Spring Boot Admin Server
spring.boot.admin.server.enabled=true

# Optional: Context path for Admin UI
spring.boot.admin.context-path=/admin

# Management endpoints exposure
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# Optional: CORS configuration
spring.boot.admin.cors.enabled=true
spring.boot.admin.cors.allowed-origins=*
